# Generated by Django 5.1.2 on 2024-10-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akbar', '0002_alter_dumpstats_full'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dumpstats',
            old_name='loc',
            new_name='name',
        ),
        migrations.AddField(
            model_name='dumpstats',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dumpstats',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
